"""Task 6.6: results/answer_report.md from the single test answer run (D-013), its judge grades, and
the judge's validation on dev (agreement with Kunal's 50 blind grades, D-034). Stops if the test
split has no answer run or more than one.

Usage: uv run python scripts/answer_report.py
"""

import json
import statistics
from pathlib import Path

from pagesight.config import SUBSETS
from pagesight.data.vidore import load_queries
from pagesight.eval.answers import answer_metrics, share
from pagesight.eval.judge import accuracy
from pagesight.eval.runner import RESULTS, git_state

THRESHOLDS = [0.4, 0.5, 0.6, 0.7]


def only(pattern: str) -> Path:
    runs = sorted(RESULTS.glob(pattern))
    if len(runs) != 1:
        raise SystemExit(
            f"{pattern}: expected exactly one file, found {len(runs)} (D-013)"
        )
    return runs[0]


def pct(x: float | None) -> str:
    return "—" if x is None else f"{100 * x:.1f}%"


def table(records: list[dict], grades: dict) -> list[str]:
    lines = [
        (
            "| | queries | correct | partial | NOT_FOUND | invalid | wrong NOT_FOUND "
            "| citation accuracy | abstention recall | NOT_FOUND precision |"
        ),
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    for name in ["all", *SUBSETS]:
        rs = records if name == "all" else [r for r in records if r["subset"] == name]
        m, acc = answer_metrics(rs), accuracy(rs, grades)
        ans = [r for r in rs if r["kind"] == "answerable"]
        not_found = share(sum(r["status"] == "not_found" for r in ans), len(ans))
        cells = [
            name,
            f"{m['answerable']} + {m['abstain']}",
            pct(acc["correct"]),
            pct(acc["partial"]),
            pct(not_found),
            pct(m["invalid"]),
            pct(m["wrong_not_found"]),
            pct(m["citation_accuracy"]),
            pct(m["abstention_recall"]),
            pct(m["not_found_precision"]),
        ]
        lines.append(f"| {' | '.join(cells)} |")
    return lines


def example(title: str, r: dict, queries: dict, grade: str | None) -> list[str]:
    q = queries[r["query"]]
    return [
        "",
        f"### {title}: `{r['query']}` ({r['kind']}, p(YES) = {r['p_yes']:.2f})",
        "",
        f"> {q.text}",
        "",
        f"- Pages shown: {', '.join(r['shown'])}; gold: {', '.join(q.gold)}",
        f"- Output: {r['output'].strip()[:400]}",
        f"- Reference: {q.answer[:400]}",
        f"- Judge: {grade or '—'}",
    ]


def main() -> None:
    dev_judge = json.loads(only("judge-dev-*.json").read_text(encoding="utf-8"))
    test_path = only("answers-test-*.json")
    test = json.loads(test_path.read_text(encoding="utf-8"))
    judge_path = RESULTS / test_path.name.replace("answers-", "judge-")
    test_judge = json.loads(judge_path.read_text(encoding="utf-8"))
    records, grades = test["records"], test_judge["grades"]
    queries = {q.id: q for s in SUBSETS for q in load_queries(s)}
    git = git_state()
    agree = dev_judge.get("agreement")
    trusted = agree is not None and agree["cohen_kappa"] >= 0.6
    lines = [
        "# Answer report (test split)",
        "",
        (
            f"Generated by `scripts/answer_report.py` at {git['commit']}"
            f"{'+dirty' if git['dirty'] else ''} from `{test['run_id']}` "
            f"({test['git']['commit']}) and `{test_judge['run_id']}` "
            f"({test_judge['git']['commit']})."
        ),
        "",
        "## Setup (locked on dev)",
        "",
        (
            f"- Answer model: `{test['config']['model']}` @ {test['config']['revision'][:7]}, 4-bit "
            f"NF4 (D-032); top {test['config']['pages_per_answer']} pages of the main visual "
            "search (D-031, D-033), each scaled to at most "
            f"{test['config']['max_pixels']:,} pixels."
        ),
        (
            f"- NOT_FOUND: a YES/NO gate answers only if p(YES) ≥ {test['config']['gate']} "
            "(D-036, D-037); the answer must cite its pages as [p:<page id>] (strict parser)."
        ),
        (
            f"- Abstention set: {test['config']['abstain_per_subset']} test queries per subset "
            "asked again with all gold pages removed; NOT_FOUND is the only correct reply."
        ),
        (
            "- Judge: the same Qwen3.5-4B, text only, grades each answer against the reference "
            "answer (D-034). Validation on dev: "
            + (
                f"{agree['n']} answers graded blind by Kunal — agreement "
                f"{agree['percent']:.1f}%, Cohen's kappa {agree['cohen_kappa']:.2f} "
                f"({'≥' if trusted else '<'} 0.6: {'trusted' if trusted else 'NOT trusted'})."
                if agree
                else "not yet run."
            )
        ),
        "",
        "## Results",
        "",
        (
            "correct / partial / NOT_FOUND / invalid: shares of the answerable queries. Wrong "
            "NOT_FOUND: refusals among answerable queries whose shown pages include a gold page. "
            "Citation accuracy: answers citing only gold pages. Abstention recall: NOT_FOUND on the "
            "gold-removed queries. NOT_FOUND precision: refusals with no gold page in view."
        ),
        "",
        *table(records, grades),
        "",
        (
            f"Latency per query (retrieval + gate + answer): p50 "
            f"{test['summary']['latency_s']['p50']} s, p95 {test['summary']['latency_s']['p95']} "
            f"s; peak VRAM {test['peak_vram_gb']} GB."
        ),
    ]
    ans = [r for r in records if r["kind"] == "answerable"]
    lines += ["", "## Reading vs retrieval", ""]
    for shown in (True, False):
        rs = [r for r in ans if r["gold_shown"] == shown]
        acc = accuracy(rs, grades)
        lines.append(
            f"- Gold page {'shown' if shown else 'not shown'} ({len(rs)} queries): correct "
            f"{pct(acc['correct'])}, partial {pct(acc['partial'])}, NOT_FOUND "
            f"{pct(share(sum(r['status'] == 'not_found' for r in rs), len(rs)))}"
        )
    shown_p = [r["p_yes"] for r in ans if r["gold_shown"]]
    removed_p = [r["p_yes"] for r in records if r["kind"] == "abstain"]
    lines += [
        "",
        "## Gate threshold trade-off (from the stored p(YES); answers exist only above 0.4)",
        "",
        "| threshold | gold shown: passes the gate | gold removed: passes the gate |",
        "|---:|---:|---:|",
    ]
    for t in THRESHOLDS:
        a = share(sum(p >= t for p in shown_p), len(shown_p))
        b = share(sum(p >= t for p in removed_p), len(removed_p))
        lines.append(f"| {t} | {pct(a)} | {pct(b)} |")
    lines += [
        "",
        (
            f"Median p(YES): gold shown {statistics.median(shown_p):.2f}, gold removed "
            f"{statistics.median(removed_p):.2f}."
        ),
        "",
        "## Examples (first by query id of each kind)",
    ]
    kinds = [
        (
            "Correct, cited",
            lambda r: (
                r["kind"] == "answerable"
                and grades.get(r["query"]) == "correct"
                and r["citations_gold"]
            ),
        ),
        (
            "Graded incorrect",
            lambda r: (
                r["kind"] == "answerable" and grades.get(r["query"]) == "incorrect"
            ),
        ),
        (
            "Correct abstention (gold removed)",
            lambda r: r["kind"] == "abstain" and r["status"] == "not_found",
        ),
        (
            "Wrong NOT_FOUND (gold shown)",
            lambda r: (
                r["kind"] == "answerable"
                and r["gold_shown"]
                and r["status"] == "not_found"
            ),
        ),
    ]
    for title, wanted in kinds:
        hit = next(
            (r for r in sorted(records, key=lambda r: r["query"]) if wanted(r)), None
        )
        if hit:
            lines += example(title, hit, queries, grades.get(hit["query"]))
    lines += [
        "",
        "## Caveats",
        "",
        (
            "- The judge is the answer model itself (text only); its agreement with Kunal is reported "
            "above."
        ),
        (
            "- Gold labels are incomplete and sometimes wrong: finance_en-q102 (human-written) names "
            "Citigroup, but its gold page and reference answer are Bank of America's (D-032)."
        ),
        (
            "- Qwen3.5's linear-attention layers run on PyTorch reference kernels here "
            "(flash-linear-attention and causal_conv1d have no Windows builds), so decoding is slow "
            "(~5 tokens/s) and the GPU is mostly idle."
        ),
    ]
    path = RESULTS / "answer_report.md"
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"saved {path.relative_to(RESULTS.parent).as_posix()}")


if __name__ == "__main__":
    main()
