"""Write results/data_stats.md: page and query statistics for the subsets in use (D-012)."""

import statistics
import struct
from collections import Counter
from pathlib import Path

from pagesight.config import ROOT, SUBSETS
from pagesight.data.split import load_split
from pagesight.data.vidore import load_pages, load_queries


def png_size(path: Path) -> str:
    with path.open("rb") as f:
        width, height = struct.unpack(">II", f.read(24)[16:])  # PNG header (IHDR)
    return f"{width}×{height}"


def table(header: list[str], rows: dict[str, list]) -> list[str]:
    lines = [
        "| " + " | ".join(header) + " |",
        "|---" + "|---:" * (len(header) - 1) + "|",
    ]
    return lines + [
        f"| {k} | " + " | ".join(map(str, v)) + " |" for k, v in rows.items()
    ]


dev = set(load_split()["dev"])
stats: dict[str, list] = {}
types: dict[str, Counter] = {}
for subset in SUBSETS:
    pages, queries = load_pages(subset), load_queries(subset)
    per_doc = Counter(p.doc_id for p in pages)
    sizes = Counter(png_size(p.image) for p in pages)
    ((size, n_size),) = sizes.most_common(1)
    gold = [len(q.gold) for q in queries]
    grades = Counter(g for q in queries for g in q.gold.values())
    generators = Counter(q.generator for q in queries)
    n_dev = sum(q.id in dev for q in queries)
    rows = {
        "pages": f"{len(pages):,}",
        "documents (pages each, min–max)": f"{len(per_doc)} "
        f"({min(per_doc.values())}–{max(per_doc.values())})",
        "most common page size, px": f"{size} ({n_size:,} of {len(pages):,} pages)",
        "pages with empty text": sum(not p.text for p in pages),
        "page text, median characters": f"{statistics.median(len(p.text) for p in pages):,.0f}",
        "English queries (dev / test)": f"{len(queries)} ({n_dev} / {len(queries) - n_dev})",
        "human / synthetic queries": f"{generators['human']} / {generators['sdg']}",
        "gold pages per query (mean / median / max)": f"{statistics.mean(gold):.1f} / "
        f"{statistics.median(gold):g} / {max(gold)}",
        "gold grades: 2 fully / 1 critically relevant": f"{grades[2]:,} / {grades[1]:,}",
    }
    for label, value in rows.items():
        stats.setdefault(label, []).append(value)
    types[subset] = Counter(t for q in queries for t in q.content_types)

order = sorted(
    set().union(*types.values()), key=lambda t: -sum(c[t] for c in types.values())
)
lines = [
    "# Data statistics",
    "",
    "Generated by `scripts/data_stats.py`. Subsets: DECISIONS.md D-012; split: D-013.",
    "",
    *table(["", *SUBSETS], stats),
    "",
    "## Query content types",
    "",
    "Number of English queries per type; a query can have several types (`content_type`).",
    "",
    *table(
        ["content type", *SUBSETS], {t: [types[s][t] for s in SUBSETS] for t in order}
    ),
]
out = ROOT / "results" / "data_stats.md"
out.parent.mkdir(exist_ok=True)
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print("\n".join(lines))
