"""Write results/go_no_go.md: visual (ColSmol) vs text baselines on the dev split (Task 3.4).

Uses the latest dev run of each config. The brief's rule: GO = visual beats BM25 on nDCG@10
AND fits in VRAM. Paired intervals show whether a gap is larger than query-sampling noise.
"""

import json

from pagesight.config import ROOT
from pagesight.eval.compare import paired_difference

RESULTS = ROOT / "results"
TEXT, VISUAL = ["bm25", "dense_qwen3"], ["colsmol_256m", "colsmol_500m"]
SUBSETS = ["hr", "finance_en"]
# ViDoRe V3 blog, all English queries (docs/DATA.md)
PUBLISHED_256M = {"hr": 0.460, "finance_en": 0.477}
VRAM_BUDGET_GB = 6.9  # free VRAM at first CUDA use (AGENTS.md)


def latest_dev_run(config: str) -> dict:
    runs = sorted(RESULTS.glob(f"{config}-dev-*.json"))  # timestamped ids sort by time
    return json.loads(runs[-1].read_text(encoding="utf-8"))


def ndcg_per_query(run: dict, subset: str) -> dict[str, float]:
    return {q: m["ndcg@10"] for q, m in run["subsets"][subset]["per_query"].items()}


def fmt(x: float) -> str:
    return f"{x:+.3f}"


runs = {c: latest_dev_run(c) for c in TEXT + VISUAL}
lines = [
    "# Go / no-go: visual vs text retrieval (dev split)",
    "",
    "Generated by `scripts/go_no_go.py` from: "
    + ", ".join(f"`{r['run_id']}`" for r in runs.values())
    + ".",
    "Δ = visual minus text nDCG@10, mean over the same queries, with a paired bootstrap 95% interval;",
    "W/T/L = queries where visual wins / ties / loses.",
    "",
    "| model | subset | nDCG@10 (95% CI) | Δ vs BM25 (95% CI) | W/T/L | Δ vs dense (95% CI) | W/T/L | peak VRAM GB |",
    "|---|---|---|---|---|---|---|---|",
]
verdicts = {}
for visual in VISUAL:
    beats_bm25, peak = [], 0.0
    for subset in SUBSETS:
        s = runs[visual]["subsets"][subset]
        low, high = s["metrics"]["ndcg@10"]["ci95"]
        mine = ndcg_per_query(runs[visual], subset)
        cells = [
            visual,
            subset,
            f"{s['metrics']['ndcg@10']['mean']:.3f} ({low:.3f}–{high:.3f})",
        ]
        for text in TEXT:
            d = paired_difference(mine, ndcg_per_query(runs[text], subset))
            cells += [
                f"{fmt(d['mean_diff'])} ({fmt(d['ci95'][0])} to {fmt(d['ci95'][1])})",
                f"{d['wins']}/{d['ties']}/{d['losses']}",
            ]
            if text == "bm25":
                beats_bm25.append(d["mean_diff"] > 0)
        cells.append(f"{s['peak_vram_gb']:.2f}")
        peak = max(peak, s["peak_vram_gb"])
        lines.append("| " + " | ".join(cells) + " |")
    verdicts[visual] = (all(beats_bm25), peak <= VRAM_BUDGET_GB, peak)

lines += [
    "",
    "## Brief's rule: visual beats BM25 on nDCG@10 (both subsets) AND fits in VRAM",
    "",
]
for visual, (beats, fits, peak) in verdicts.items():
    lines.append(
        f"- **{visual}**: beats BM25 on both subsets: {'yes' if beats else 'no'}; "
        f"fits in VRAM: {'yes' if fits else 'no'} (peak {peak:.2f} of {VRAM_BUDGET_GB} GB)"
    )

ours = runs["colsmol_256m"]["subsets"]
lines += [
    "",
    "## Sanity check: ColSmol-256M vs published numbers (all English queries; ours = dev, 30%)",
    "",
    *(
        f"- {s}: ours {ours[s]['metrics']['ndcg@10']['mean']:.3f} vs published {PUBLISHED_256M[s]:.3f}"
        for s in SUBSETS
    ),
]
(RESULTS / "go_no_go.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
print("\n".join(lines))
