"""Group 6 evidence for the NOT_FOUND rule: does the top retrieval score separate answerable dev
queries from the same queries with all their gold pages removed (the abstention set, Task 6.3)?
Scores are Qdrant exact MaxSim (D-031), raw and divided by the number of query tokens (MaxSim sums
over tokens, so longer questions score higher). AUC = chance that a random answerable query scores
above a random gold-removed one (0.5 = no separation, 1.0 = perfect).

Usage: uv run python scripts/probe_abstain.py -> results/abstain_probe.md
"""

import statistics

from qdrant_client import models

from pagesight.config import SUBSETS
from pagesight.data.split import load_split
from pagesight.data.vidore import load_queries
from pagesight.eval.runner import RESULTS, git_state
from pagesight.index.qdrant_store import connect
from pagesight.retrieval.colsmol import embed_query, load_model
from pagesight.search.two_stage import EXACT


def auc(pos: list[float], neg: list[float]) -> float:
    wins = sum((p > n) + 0.5 * (p == n) for p in pos for n in neg)
    return wins / (len(pos) * len(neg))


def best_split(pos: list[float], neg: list[float]) -> tuple[float, float]:
    """Threshold with the best balanced accuracy (mean of the two hit rates), and that accuracy."""
    cuts = sorted(set(pos + neg))
    scored = [
        (
            (sum(p >= t for p in pos) / len(pos) + sum(n < t for n in neg) / len(neg))
            / 2,
            t,
        )
        for t in cuts
    ]
    acc, t = max(scored)
    return t, acc


def main() -> None:
    dev = set(load_split()["dev"])
    model, processor = load_model("vidore/colSmol-500M")  # D-023
    client = connect()
    git = git_state()
    lines = [
        "# Abstention probe: top retrieval score with and without the gold pages (dev)",
        "",
        (
            f"Generated by `scripts/probe_abstain.py` at {git['commit']}"
            f"{'+dirty' if git['dirty'] else ''}; Qdrant exact MaxSim (D-031)."
        ),
        "",
        (
            "| subset | queries | median raw (answerable / removed) | AUC raw | AUC per token "
            "| best balanced accuracy per token (threshold) |"
        ),
        "|---|---:|---|---:|---:|---|",
    ]
    for subset in SUBSETS:
        raw = {"pos": [], "neg": []}
        per_token = {"pos": [], "neg": []}
        queries = [q for q in load_queries(subset) if q.id in dev]
        for q in queries:
            vec = embed_query(model, processor, q.text).float().cpu()
            gold_ids = [int(p.rsplit("-", 1)[1]) for p in q.gold]
            removed = models.Filter(must_not=[models.HasIdCondition(has_id=gold_ids)])
            for key, query_filter in (("pos", None), ("neg", removed)):
                hit = client.query_points(
                    subset,
                    vec.tolist(),
                    using="patches",
                    limit=1,
                    query_filter=query_filter,
                    search_params=EXACT,
                ).points[0]
                raw[key].append(hit.score)
                per_token[key].append(hit.score / len(vec))
        t, acc = best_split(per_token["pos"], per_token["neg"])
        cells = [
            subset,
            len(queries),
            f"{statistics.median(raw['pos']):.2f} / {statistics.median(raw['neg']):.2f}",
            f"{auc(raw['pos'], raw['neg']):.3f}",
            f"{auc(per_token['pos'], per_token['neg']):.3f}",
            f"{acc:.3f} ({t:.4f})",
        ]
        lines.append(f"| {' | '.join(map(str, cells))} |")
        print(lines[-1])
    client.close()
    (RESULTS / "abstain_probe.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
