"""Group 5 evidence: does one mean-pooled vector per page keep the exact MaxSim top-10 in its top N?
Dev queries only. Stage 1 ranks pages by pooled vector (Dot, or Cosine = pooled vector normalised)
against the mean query vector; stage 2 reranks the top N with exact MaxSim.

Usage: uv run python scripts/probe_pooling.py -> results/pooling_probe.md
"""

import statistics

import torch

from pagesight.config import SUBSETS
from pagesight.data.split import load_split
from pagesight.data.vidore import load_pages, load_queries
from pagesight.eval.metrics import query_metrics
from pagesight.eval.runner import RESULTS, git_state
from pagesight.retrieval.colsmol import ColSmolRetriever, embed_query
from pagesight.retrieval.maxsim import maxsim

MODEL = "vidore/colSmol-500M"  # D-023
NS = [10, 25, 50, 100, 200, 400]
K = 10


def main() -> None:
    dev = set(load_split()["dev"])
    git = git_state()
    lines = [
        "# Pooled first-stage probe",
        "",
        (
            f"Generated by `scripts/probe_pooling.py` at {git['commit']}"
            f"{'+dirty' if git['dirty'] else ''}: {MODEL}, dev queries only."
        ),
        '"kept" = share of the exact MaxSim top-10 found in the first-stage top N; nDCG@10 is after',
        "reranking those N pages with exact MaxSim.",
    ]
    for subset in SUBSETS:
        queries = [q for q in load_queries(subset) if q.id in dev]
        r = ColSmolRetriever(load_pages(subset), MODEL, batch_size=1)
        # padding rows are zero, so the sum over all rows is the sum over real patches
        mean = r.pages.sum(dim=1) / r.mask.sum(dim=1, keepdim=True)
        pooled = {"Dot": mean, "Cosine": torch.nn.functional.normalize(mean, dim=-1)}
        kept = {(p, n): [] for p in pooled for n in NS}
        ndcg = {(p, n): [] for p in pooled for n in NS}
        exact_ndcg = []
        for q in queries:
            vec = embed_query(r.model, r.processor, q.text).float()
            exact = maxsim(vec, r.pages, r.mask)
            top = exact.topk(K).indices
            exact_ndcg.append(
                query_metrics([r.ids[i] for i in top.tolist()], q.gold)["ndcg@10"]
            )
            for p, vectors in pooled.items():
                order = (vectors @ vec.mean(dim=0)).argsort(descending=True)
                for n in NS:
                    cand = order[:n]
                    kept[(p, n)].append(torch.isin(top, cand).float().mean().item())
                    best = cand[exact[cand].topk(min(K, n)).indices]
                    ranking = [r.ids[i] for i in best.tolist()]
                    ndcg[(p, n)].append(query_metrics(ranking, q.gold)["ndcg@10"])
        lines += [
            "",
            (
                f"## {subset}: {len(queries)} queries, {len(r.ids)} pages; "
                f"exact MaxSim nDCG@10 {statistics.fmean(exact_ndcg):.3f}"
            ),
            "",
            "| N | % of pages | kept, Dot | kept, Cosine | nDCG@10, Dot | nDCG@10, Cosine |",
            "|---:|---:|---:|---:|---:|---:|",
        ]
        for n in NS:
            cells = [n, f"{100 * n / len(r.ids):.1f}"]
            cells += [f"{statistics.fmean(kept[(p, n)]):.3f}" for p in pooled]
            cells += [f"{statistics.fmean(ndcg[(p, n)]):.3f}" for p in pooled]
            lines.append(f"| {' | '.join(map(str, cells))} |")
        print("\n".join(lines[-len(NS) - 4 :]))
        del r
        torch.cuda.empty_cache()  # one model on the GPU at a time
    (RESULTS / "pooling_probe.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
