"""Measure ColSmol embedding speed and peak VRAM per batch size -> results/colsmol_probe.md
(Task 3.1: batch size chosen by measurement)."""

import time

import torch

from pagesight.config import ROOT
from pagesight.data.vidore import load_pages
from pagesight.retrieval.colsmol import MODELS, embed_pages, load_model

pages = load_pages("hr")[:16] + load_pages("finance_en")[:16]  # A4 and letter pages
lines = [
    "# ColSmol batch-size probe",
    "",
    "Generated by `scripts/probe_colsmol.py`: 32 pages (16 hr A4 + 16 finance_en letter), bf16, RTX 4060 Laptop.",
    "Peak VRAM is `torch.cuda.max_memory_allocated` (excludes the ~1 GB CUDA context, see AGENTS.md).",
    "",
    "| model | batch | pages/s | peak VRAM GB | vectors per page (hr / finance_en) |",
    "|---|---:|---:|---:|---|",
]
for name in MODELS:
    model, processor = load_model(name)
    embed_pages(model, processor, pages[:2], 1)  # warm-up: first CUDA calls are slow
    for batch in (1, 2, 4, 8):
        torch.cuda.empty_cache()
        torch.cuda.reset_peak_memory_stats()
        torch.cuda.synchronize()
        start = time.perf_counter()
        try:
            vectors = embed_pages(model, processor, pages, batch)
        except torch.cuda.OutOfMemoryError:
            lines.append(f"| {name} | {batch} | out of memory | | |")
            print(lines[-1])
            break
        torch.cuda.synchronize()
        speed = len(pages) / (time.perf_counter() - start)
        peak = torch.cuda.max_memory_allocated() / 2**30
        lines.append(
            f"| {name} | {batch} | {speed:.1f} | {peak:.2f} | {len(vectors[0])} / {len(vectors[16])} |"
        )
        print(lines[-1])
    del model
    torch.cuda.empty_cache()
(ROOT / "results" / "colsmol_probe.md").write_text(
    "\n".join(lines) + "\n", encoding="utf-8"
)
