"""Group 5 evidence: which cheap first stage keeps the exact MaxSim top-10 in its top N?
Dev queries only. Each first stage ranks all pages; the top N are reranked with exact MaxSim.
- mean: one mean-pooled vector per page vs the mean query vector (Dot; Cosine = normalised)
- binary: MaxSim against the sign (1 bit) of each patch vector, with a float or a 1-bit query
- window w: MaxSim against the means of w consecutive patch vectors (~1/w of the vectors)

Usage: uv run python scripts/probe_pooling.py -> results/pooling_probe.md
"""

import statistics

import torch
import torch.nn.functional as F

from pagesight.config import SUBSETS
from pagesight.data.split import load_split
from pagesight.data.vidore import load_pages, load_queries
from pagesight.eval.metrics import query_metrics
from pagesight.eval.runner import RESULTS, git_state
from pagesight.retrieval.colsmol import ColSmolRetriever, embed_query
from pagesight.retrieval.maxsim import maxsim

MODEL = "vidore/colSmol-500M"  # D-023
NS = [25, 50, 100, 200, 400]
K = 10
CHUNK = 512  # pages per GPU step for the binary copy, to bound memory
STAGES = [
    "mean, Dot",
    "mean, Cosine",
    "binary, float query",
    "binary, 1-bit query",
    "window 16",
    "window 64",
]


def window_pool(
    pages: torch.Tensor, mask: torch.Tensor, w: int
) -> tuple[torch.Tensor, torch.Tensor]:
    """Mean of each run of w consecutive patch vectors; padding rows are zero, so sums skip them."""
    n, p, d = pages.shape
    pages = F.pad(pages, (0, 0, 0, -p % w))
    mask = F.pad(mask, (0, -p % w))
    counts = mask.view(n, -1, w).sum(dim=2)
    pooled = pages.view(n, -1, w, d).sum(dim=2) / counts.clamp(min=1)[..., None]
    return pooled, counts > 0


def chunked_maxsim(
    q: torch.Tensor, pages: torch.Tensor, mask: torch.Tensor
) -> torch.Tensor:
    return torch.cat(
        [
            maxsim(q, pages[i : i + CHUNK].float(), mask[i : i + CHUNK])
            for i in range(0, len(pages), CHUNK)
        ]
    )


def main() -> None:
    dev = set(load_split()["dev"])
    git = git_state()
    lines = [
        "# First-stage probe",
        "",
        (
            f"Generated by `scripts/probe_pooling.py` at {git['commit']}"
            f"{'+dirty' if git['dirty'] else ''}: {MODEL}, dev queries only."
        ),
        "Each first stage ranks all pages; its top N are reranked with exact MaxSim.",
        '"kept" = share of the exact MaxSim top-10 inside the first-stage top N.',
    ]
    for subset in SUBSETS:
        queries = [q for q in load_queries(subset) if q.id in dev]
        r = ColSmolRetriever(load_pages(subset), MODEL, batch_size=1)
        mean = r.pages.sum(dim=1) / r.mask.sum(dim=1, keepdim=True)
        binary = torch.cat(
            [
                torch.sign(r.pages[i : i + CHUNK]).to(torch.int8)
                for i in range(0, len(r.pages), CHUNK)
            ]
        )
        windows = {w: window_pool(r.pages, r.mask, w) for w in (16, 64)}
        kept = {(s, n): [] for s in STAGES for n in NS}
        ndcg = {(s, n): [] for s in STAGES for n in NS}
        exact_ndcg = []
        for q in queries:
            vec = embed_query(r.model, r.processor, q.text).float()
            exact = maxsim(vec, r.pages, r.mask)
            top = exact.topk(K).indices
            ranking = [r.ids[i] for i in top.tolist()]
            exact_ndcg.append(query_metrics(ranking, q.gold)["ndcg@10"])
            first = [
                mean @ vec.mean(dim=0),
                F.normalize(mean, dim=-1) @ vec.mean(dim=0),
                chunked_maxsim(vec, binary, r.mask),
                chunked_maxsim(torch.sign(vec), binary, r.mask),
                maxsim(vec, *windows[16]),
                maxsim(vec, *windows[64]),
            ]
            for s, scores in zip(STAGES, first, strict=True):
                order = scores.argsort(descending=True)
                for n in NS:
                    cand = order[:n]
                    kept[(s, n)].append(torch.isin(top, cand).float().mean().item())
                    best = cand[exact[cand].topk(K).indices]
                    ranking = [r.ids[i] for i in best.tolist()]
                    ndcg[(s, n)].append(query_metrics(ranking, q.gold)["ndcg@10"])
        vectors = (
            f"vectors per page in stage 1: mean 1, window 16 {windows[16][1].sum(1).float().mean():.0f}, "
            f"window 64 {windows[64][1].sum(1).float().mean():.0f}, "
            f"binary {r.mask.sum(1).float().mean():.0f} at 1 bit each"
        )
        lines += [
            "",
            (
                f"## {subset}: {len(queries)} queries, {len(r.ids)} pages; "
                f"exact MaxSim nDCG@10 {statistics.fmean(exact_ndcg):.3f}"
            ),
            "",
            vectors,
        ]
        for name, values in (("kept", kept), ("nDCG@10", ndcg)):
            lines += [
                "",
                f"| {name}: N (% of pages) | {' | '.join(STAGES)} |",
                f"|---|{'---:|' * len(STAGES)}",
            ]
            for n in NS:
                cells = [f"{n} ({100 * n / len(r.ids):.1f}%)"]
                cells += [f"{statistics.fmean(values[(s, n)]):.3f}" for s in STAGES]
                lines.append(f"| {' | '.join(cells)} |")
        print("\n".join(lines[lines.index(vectors) - 2 :]))
        del r, binary, windows, mean
        torch.cuda.empty_cache()  # one model on the GPU at a time
    (RESULTS / "pooling_probe.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
